# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme_name: bluegreen
# theme: jekyll-theme-bluegreen-0.1.1
author: Björn Kawecki

title: E-portfolio
subtitle: Élève-ingénieur en sciences du numérique
name: Samir Tamboura

email: samir.tamboura@etu.inp-n7.fr
description: J'espère que vous apprecierez découvrir monn parcours,mes projets et mes objectifs pour le futur dans ce site.
url: "https://samirkema.github.io" 
baseurl: "/e-portfolio"  
twitter_username:
github_username: samirkema
linkedin_username: Samir Kemayou Tamboura

plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-paginate

postcss:
  cache: false

paginate: 5
paginate_path: "/page:num/"

collections:
  projects:
    output: true   # Falls du möchtest, dass jedes Projekt eine eigene Seite hat
    permalink: /projects/:path/

sass:
  load_paths:
    - _sass
    - node_modules

include:
  - node_modules/tailwindcss
  - _pages

kramdown:
  smart_quotes: sbquo,rsquo,bdquo,rdquo
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
